version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always 
    environment:
      MYSQL_DATABASE: tedexdb
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - "3306:3306"
    networks:
      - django-test


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 'true'
      DATABASE_URL: mysql://admin:test1234@tedexdb.cxg84s662tyk.us-east-2.rds.amazonaws.com:3306/tedexd
    networks:
      - django-test

volumes:
  data:

networks:
  django-test: {}