apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: 730335380624.dkr.ecr.us-east-2.amazonaws.com/tedex-repo:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql://admin:test1234@tedexdb.cxg84s662tyk.us-east-2.rds.amazonaws.com:3306/tedexdb"  # Replace with your actual database URL
        - name: DJANGO_SETTINGS_MODULE
          value: "project.settings"  # Replace with your actual settings module
